environment_name: "LunarLander-v3"
labels: 
  - ["x", "y", "vx", "vy", "θ", "ω", "leg_L", "leg_R"]
  - ["Nothing", "Fire Left", "Fire Main", "Fire Right"]

architecture:
  - 8
  - 6
  - 4

algorithm:
  population_size: 100
  num_generations: 300

  algorithm: "mu_plus_lambda"
  mu: 100
  lambda_: 200
  
  elite_size: 10
  num_eval_episodes: 5
  
  crossover:
    method: "simulated_binary"
    probability: 0.5
    eta: 15.0
  
  mutation:
    method: "polynomial_bounded"
    probability: 0.5
    eta: 15.0
    low: -20.0
    up: 20.0
    # indpb: 0.02
  
  selection:
    method: "tournament"
    tournsize: 3
  
  random_seed: null
  n_workers: null
  verbose: true

success_threshold: 200.0
experiments_dir: "results"