environment_name: "LunarLander-v3"
labels: 
  - ["x", "y", "vx", "vy", "θ", "ω", "leg_L", "leg_R"]
  - ["Nothing", "Fire Left", "Fire Main", "Fire Right"]

architecture:
  - 8
  - 6
  - 4

algorithm:
  population_size: 60
  num_generations: 100

  algorithm: "mu_comma_lambda"
  mu: 60
  lambda_: 360
  
  elite_size: 10
  num_eval_episodes: 5
  
  crossover:
    method: "blend_es"
    probability: 0.0
    alpha: 0.1
  
  mutation:
    method: "log_normal_es"
    probability: 1.0
    c: 0.6
    indpb: 1.0
  
  selection:
    method: "best"
    # k: 10
  
  random_seed: null
  n_workers: null
  verbose: true

success_threshold: 200.0
experiments_dir: "results"