environment_name: "LunarLander-v3"
labels: 
  - ["x", "y", "vx", "vy", "θ", "ω", "leg_L", "leg_R"]
  - ["Nothing", "Fire Left", "Fire Main", "Fire Right"]

architecture:
  - 8
  - 6
  - 4

algorithm:
  population_size: 100
  num_generations: 300

  algorithm: "mu_comma_lambda"
  mu: 100
  lambda_: 200
  
  elite_size: 10
  num_eval_episodes: 5
  
  crossover:
    method: "blend"
    probability: 0.75
    alpha: 0.5
  
  mutation:
    method: "gaussian"
    probability: 0.25
    mu: 0.0
    sigma: 1.0
    # indpb: 0.02
  
  selection:
    method: "tournament"
    tournsize: 4
  
  random_seed: null
  n_workers: null
  verbose: true

success_threshold: 200.0
experiments_dir: "experiments"